"""Shared matplotlib style for every figure of the study.

Every figure in the thesis is generated by scripts/06_make_figures.py through
this style, so the eight PDFs read as one set: same fonts, same sizes, same
palette, same margins.

Sizing is measured, not guessed: the document is A4 with 3cm margins, so
\\textwidth is exactly 15cm = 426.79pt = 5.906in (confirmed in main.log). A
figure drawn at that width and included at \\textwidth is reproduced 1:1, which
is the only way its labels end up the same size as the body text. Drawing
narrower and letting LaTeX scale up shrinks the figure's fonts by the same
factor -- the opposite of what matching fonts means.

Exports:
  - FIGURE_WIDTH and the derived heights for the layouts in use
  - apply_style(): install the rcParams, optionally with usetex
  - COLORS, EVENT_COLOR, SEQUENTIAL_CMAP, DIVERGING_CMAP

Integration: called once at the top of scripts/06_make_figures.py, and by the
  Streamlit app of Sprint 6 so the on-screen figures match the printed ones.
Why usetex defaults to False: MiKTeX is slow and fragile when invoked in a loop
  which makes it painful during development. It is turned
  on only for the final run of S5.3, where the font match must be exact.
"""
from __future__ import annotations

import matplotlib as mpl

# \textwidth of the thesis: A4 (21cm) less 3cm margins = 15cm = 426.79pt.
FIGURE_WIDTH = 5.906
# Golden-ratio-ish single panel, and the taller stacks used by the multi-panel
# figures. Kept here so no script invents its own aspect ratio.
FIGURE_HEIGHT = FIGURE_WIDTH / 1.618
# One panel of a stacked, shared-axis figure. Four of them come to 7.0in, well
# inside the 9.33in of A4 text height, so the central figure of Section 6.6 can
# breathe on its own page instead of being split -- splitting it would break the
# one reading it exists for, comparing all four metrics at a single date.
STACK_PANEL_HEIGHT = 1.75
WIDE_PANEL_HEIGHT = FIGURE_WIDTH / 2.6

# Qualitative palette for series drawn on the same axes. Chosen to stay
# distinguishable in grayscale print, since the thesis may be printed in b/w.
COLORS = (
    "#1f4e79",  # deep blue
    "#c1512d",  # terracotta
    "#4c7a34",  # olive
    "#7b5aa6",  # violet
)
# Event markers are deliberately outside the series palette: a vertical rule
# must never be mistaken for one of the plotted quantities.
EVENT_COLOR = "#6b6b6b"

SEQUENTIAL_CMAP = "viridis"
# Correlation heatmaps are diverging around 0 and always scaled to [-1, 1].
DIVERGING_CMAP = "RdBu_r"


def apply_style(usetex: bool = False) -> None:
    """Install the study's rcParams globally.

    Font sizes are set for a figure reproduced at 1:1 inside a 12pt document:
    labels a little smaller than the body, ticks smaller still, which is what
    keeps a full-width figure from shouting over the text around it.

    With `usetex=False` the closest available match to the document's Computer
    Modern is a serif family with the `cm` mathtext fontset -- the preamble
    loads no font package, so the document is Latin Modern at 12pt. With
    `usetex=True` the text is typeset by LaTeX itself and the match is exact.
    """
    mpl.rcParams.update(
        {
            "figure.figsize": (FIGURE_WIDTH, FIGURE_HEIGHT),
            "figure.dpi": 150,
            "savefig.dpi": 300,
            "savefig.bbox": "tight",
            "savefig.pad_inches": 0.02,
            # Type 42 embeds TrueType rather than Type 3 bitmapped fonts, which
            # some publishers and PDF/A checks reject.
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "font.family": "serif",
            "font.serif": ["CMU Serif", "Latin Modern Roman", "DejaVu Serif"],
            "mathtext.fontset": "cm",
            "font.size": 9,
            "axes.titlesize": 9,
            "axes.labelsize": 9,
            "xtick.labelsize": 8,
            "ytick.labelsize": 8,
            "legend.fontsize": 8,
            "figure.titlesize": 10,
            "axes.grid": True,
            "grid.alpha": 0.25,
            "grid.linewidth": 0.5,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.linewidth": 0.7,
            "lines.linewidth": 1.1,
            "legend.frameon": False,
            "text.usetex": usetex,
        }
    )
